---
- hosts: localhost
  gather_facts: no
  tasks:

  - name: fdisk
    shell: /bin/echo -e "d\n3\nn\n3\n\n\nN\nw" | sudo fdisk /dev/sda

  - name: pvresize
    shell: pvresize /dev/sda3

  - name: lvextend
    lvol: 
      vg: ubuntu-vg
      lv: ubuntu-lv
      size: 100%FREE
      resizefs: true
